# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  # - name: Home
  #   url: '#about'
  #   weight: 10
  - name: Scholar
    url: https://scholar.google.com/citations?user=_7QnJiEAAAAJ&hl=en
    weight: 10
  - name: Writer
    url: '#posts'
    weight: 20
  - name: Musician
    url: https://adamsaffron.bandcamp.com/
    weight: 25
  # - name: Talks
  #   url: '#talks'
  #   weight: 40


# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
 # - name: CV
 #   url: uploads/CV.pdf
 #   weight: 70
