---
title: Presocratic Monism
author: Adam Sadowski
date: '2022-11-09'
slug: presocratic-monism
categories: []
tags: []
subtitle: ''
summary: ''
authors: []
lastmod: '2022-11-09T19:42:00-05:00'
featured: no
projects: []
---

Order was, is, and shall be an ever-living fire.[^1] The questions of this paper: "Why fire? Why that specific 'element' or metaphor? Does Heraclitus mean to say that Order is luminous (enlightening), warming (comforting), destructive, proportional?" I argue that this is in fact the case.

Why is Order enlightening? First, it would be duly to note the availability of its enlightenment: Heraclitus says Order is apprehensible to all: "Everyone has the potential for self-knowledge and sound thinking."[2] If 'Order as fire' is behind everything, as suggested by the idea of 'fire as being compensated for and as compensation', and fire as "One-in-many", then as self-knowledge and sound thinking occur, Order is being grasped.[iii] But why does not all knowledge and thinking grasp Order? The distinguishing characteristic of the kind of knowledge that grasps Order is truth; For Heraclitus speaks of many people as being ignorant of true knowledge: According to him, the general run of people do not know what they are doing, behaving as if they are absent, as though they had private understanding, and are ignorant of an underlying harmony.[iv] If everyone has the potential for sound thinking, and true understanding is that which is commonly available (rather than privately), and if harmony underlies the world, there must be a truth-characterized Order, apprehensible by all, that is not always grasped given that it is underlying. Order is enlightening in that it is 1) characterized by truth, and 2) illuminative of the darkness that is our ignorance (of the underlying).

And this enlightenment is comforting, just as a luminous fire is warming. A fiery Order is used to contrast against the wet Chaos abiding in one who overindulges in drink and sex (and likely food as well, given that all three are composed of moisture): A drunk person is "ignorant of his route" (lacking luminosity) and of a "moist soul" (lacking comfortable dryness that is available through warmth);[v] The orgiastic Dionysus (along with his overabundance of expelled sexual juices) is the same as hellish Hades (who rules over the dead in a dark and unpleasant setting) – Notwithstanding godliness, to praise Dionysus through certain processions is disgraceful;[vi] And frankly, "a dry soul, a beam of light, is wisest and best."[vii] Heraclitus thus wishes to promote temperance – and perhaps even asceticism – through 'Order as fire': For him, man warmed by fire is more ordered and behaves more orderly than man wetted by too many pleasures; For he who is dry is more comfortable and less preoccupied than he who is wet; For he who is wet is more susceptible of acquiring sickness.

But 'Order as fire' is not all happy news. It is enlightening, comforting, but also destructive. It underlies and embodies a constant changing in the world, so that changes ultimately "make no difference": More perspicuously, changes make no difference to Order since they are themselves embodiments of Order; For the first principle (Order) to change, a preliminary principle would have to allow the change – But no principle can be preliminary to the first By claiming that changes "make no difference", Heraclitus employs ironic wordplay to communicate something contrary to our intuitions, namely that the destruction of things like life, sleep and youth, in (ultimate) reality, make no difference; Order is inherent in the unpalatable and distressing, notwithstanding our feeling that they are continually making a difference to our personal experiences. Heraclitus takes his irony to its extreme conclusion, saying that destructive wars are just and necessary – Here, in more acts of wordplay, 'war' may simply be a metaphor for 'strife', and 'just' for 'ordered'. Fortunately the realization that destruction is ordered results in useful understanding: Given that Order is destructive, it is self-defeating and unreasonably idealistic to attempt to eliminate destruction entire; Some form of it shall always remain. This is not to say that we ought not to attempt to eliminate some forms of destruction; Heraclitus makes a value claim that is certainly prescriptive: "It is more important to quench insolence than a conflagration."[ix] So it is better for people to be respectful and mannerly, and thereby avoid certain destructions of comfort, than to futilely attempt the elimination of all destruction. Through such a value claim, Heraclitus encourages differentiation between inevitable and preventable forms of destruction so that we may soundly judge which destructions we ought to attempt to avoid (e.g. the transience of life, sleep and youth cannot be avoided, whereas the personal tumult of the pleasure-seeker can).

Order is never disproportionately destructive, however, just as fire is never disproportionate to its material supply. Order is fire because fire is the measurable and proportionate transformation of things in tension:[x] "[Order] always was and is and shall be an ever-living fire, flaring up in regular measures and dying down in regular measures."[xi] Here 'regular measures' is suggestive of symmetry, periodical-ness and proportionality – Indeed, fire is an exchange of matter that "gives as much as it takes", and is thus proportional.[xii] It is Heraclitus' idea that Order too might inherently involve proportionality, and there is no better symbol for proportionate change than fire.

The 'Order as fire' metaphor predates some of the ideas of other Presocratic thinkers. Order as an ever-living fire predates and perhaps influenced the "unborn and imperishable" characteristics of Parmenides' "what-is"; Ever-livingness defies birth and perishing.[xiii] Order as proportionate predates and perhaps influenced Pythagoras' numeral conception of the knowable: Pythagoras thought that without number "it would be impossible for anything to be the object of thought or knowledge", leading him to conclude that all objects or things must have number; And if all things have number, then all things are in ratio (or proportion) to one another. Heraclitus deemed the things (manifestations) of Order proportionate; and the Pythagoreans may have brought this idea to its logical conclusion: Whatever is proportionate must also be numeral. 

Heraclitus' metaphor also echoes a thought shared by Anaximander, Parmenides and Zeno: Mere perception is not enough to understand the world. If perception only works with bounded objects, it cannot grasp the first principle behind these objects (Anaximander's apeiron);[xiv] If perception involves the separation of being such that we perceive multiple things, then it is leading us astray from the singular and continuous nature of being (Parmenides' monism);[xv] Perception misguides us into believing that motion is an actual reality, preventing us from appreciating the underlying motionless unity of the world (see Zeno's paradox); And to repeat, Heraclitus thinks that most people – who doubtless have perception – are ignorant of an underlying harmony, and so perception must not be enough to understand the world's first principle.4

The implications of this study are manifold if it is agreed that an underlying order of sorts (as a first principle or as an imposition of the mind) is enlightening, comforting, destructive and proportional; What follows is both theoretical and practical wisdom: True knowledge goes further than perception, is rare (in attainment) and yet common (in attainability) to all; Temperance is needed to reach one's fullest potential as a human being; Ultimate reality is unaffected by change, and yet certain changes within our control ought to be enacted; And understanding our world involves the use of the concept of proportionality.

And if not accepted as truth-bearing, the 'Order as fire' metaphor has aesthetic value. Not only does fire encapsulate enlightenment, comfort, destruction and proportionality; these encapsulations are also intimately relatable: Most of us (human beings of the past and present) have experienced them sentimentally, and some quite profoundly: In war-time we have candle-lighted our way through underground tunnels and food-cellars; We have avoided sickness and death through make-shift fires; We have had our homes destroyed in burning; We have had to gather enough firewood to keep our friends and families warm through the night. Apart from its intimate relatability, fire is imaginative, shocking, intense and passionate; it has been used to describe both love and hatred; it is often everything a poetic thinker, speaker or writer wants from a metaphor. One of the greatest implications of this study is the necessary result of having uncovered (an understanding of) true artistry: the acquisition of good taste and an ability to share it.

[^1]: Waterfield, Robin. The First Philosophers: The Presocratics and Sophists. Oxford: Oxford UP, 2000. Print. F36, pp41-42.

[ii] Ibid., F31, p41.

[iii] Ibid., F38, p42. Copleston, Frederick Charles John Paul. A History of Philosophy: Volume 1: Greece and Rome. London: Burns and Oates, 1947. Print. p40.

[iv] Waterfield, Robin. The First Philosophers: The Presocratics and Sophists. Oxford: Oxford UP, 2000. Print. F1, 5, 6, 21, pp37-40.

[v] Ibid., F45, p44.

[vi] Ibid., F63, p46.

[vii] Ibid., F47, p44.

[viii] Ibid., F13, p39.

[ix] Ibid., F58, p46.

[x] Copleston, Frederick Charles John Paul. A History of Philosophy: Volume 1: Greece and Rome. London: Burns and Oates, 1947. Print. p41.

[xi] Waterfield, Robin. The First Philosophers: The Presocratics and Sophists. Oxford: Oxford UP, 2000. Print. F36, p42.

[xii] Copleston, Frederick Charles John Paul. A History of Philosophy: Volume 1: Greece and Rome. London: Burns and Oates, 1947. Print. p41.

[xiii] Waterfield, Robin. The First Philosophers: The Presocratics and Sophists. Oxford: Oxford UP, 2000. Print. F8, p59.

[xiv] Ibid., T15, p14.

[xv] Ibid., F8, p59.

Bibliography:

Waterfield, Robin. The First Philosophers: The Presocratics and Sophists. Oxford: Oxford UP, 2000. Print. Copleston, Frederick Charles John Paul. A History of Philosophy: Volume 1: Greece and Rome. London: Burns and Oates, 1947. Print.

Waterfield, Robin. The First Philosophers: The Presocratics and Sophists. Oxford: Oxford UP, 2000. Print. F36, pp41-42.
